FROM golang:latest
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends unzip libwebp-dev python3-venv python3-pip clang libsharpyuv-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /tmp
RUN curl -fsSL https://deb.nodesource.com/setup_25.x | bash - && apt-get install -y --no-install-recommends nodejs && node -v

#uncomment below if you want to compile during build
#RUN git clone https://github.com/tronbyt/pixlet.git
#WORKDIR /tmp/pixlet
#RUN npm install && npm run build && make build

CMD ["bash"]