// Code generated by "enumer -type PadAlign -trimprefix Align -transform lower"; DO NOT EDIT.

package strings

import (
	"fmt"
	"strings"
)

const _PadAlignName = "startend"

var _PadAlignIndex = [...]uint8{0, 5, 8}

const _PadAlignLowerName = "startend"

func (i PadAlign) String() string {
	if i >= PadAlign(len(_PadAlignIndex)-1) {
		return fmt.Sprintf("PadAlign(%d)", i)
	}
	return _PadAlignName[_PadAlignIndex[i]:_PadAlignIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PadAlignNoOp() {
	var x [1]struct{}
	_ = x[AlignStart-(0)]
	_ = x[AlignEnd-(1)]
}

var _PadAlignValues = []PadAlign{AlignStart, AlignEnd}

var _PadAlignNameToValueMap = map[string]PadAlign{
	_PadAlignName[0:5]:      AlignStart,
	_PadAlignLowerName[0:5]: AlignStart,
	_PadAlignName[5:8]:      AlignEnd,
	_PadAlignLowerName[5:8]: AlignEnd,
}

var _PadAlignNames = []string{
	_PadAlignName[0:5],
	_PadAlignName[5:8],
}

// PadAlignString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PadAlignString(s string) (PadAlign, error) {
	if val, ok := _PadAlignNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PadAlignNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PadAlign values", s)
}

// PadAlignValues returns all values of the enum
func PadAlignValues() []PadAlign {
	return _PadAlignValues
}

// PadAlignStrings returns a slice of all String values of the enum
func PadAlignStrings() []string {
	strs := make([]string, len(_PadAlignNames))
	copy(strs, _PadAlignNames)
	return strs
}

// IsAPadAlign returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PadAlign) IsAPadAlign() bool {
	for _, v := range _PadAlignValues {
		if i == v {
			return true
		}
	}
	return false
}
