// Code generated by "enumer -type ImageFormat -trimprefix Image -transform lower -output image_format_string.go"; DO NOT EDIT.

package loader

import (
	"fmt"
	"strings"
)

const _ImageFormatName = "webpgif"

var _ImageFormatIndex = [...]uint8{0, 4, 7}

const _ImageFormatLowerName = "webpgif"

func (i ImageFormat) String() string {
	if i >= ImageFormat(len(_ImageFormatIndex)-1) {
		return fmt.Sprintf("ImageFormat(%d)", i)
	}
	return _ImageFormatName[_ImageFormatIndex[i]:_ImageFormatIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ImageFormatNoOp() {
	var x [1]struct{}
	_ = x[ImageWebP-(0)]
	_ = x[ImageGIF-(1)]
}

var _ImageFormatValues = []ImageFormat{ImageWebP, ImageGIF}

var _ImageFormatNameToValueMap = map[string]ImageFormat{
	_ImageFormatName[0:4]:      ImageWebP,
	_ImageFormatLowerName[0:4]: ImageWebP,
	_ImageFormatName[4:7]:      ImageGIF,
	_ImageFormatLowerName[4:7]: ImageGIF,
}

var _ImageFormatNames = []string{
	_ImageFormatName[0:4],
	_ImageFormatName[4:7],
}

// ImageFormatString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ImageFormatString(s string) (ImageFormat, error) {
	if val, ok := _ImageFormatNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ImageFormatNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ImageFormat values", s)
}

// ImageFormatValues returns all values of the enum
func ImageFormatValues() []ImageFormat {
	return _ImageFormatValues
}

// ImageFormatStrings returns a slice of all String values of the enum
func ImageFormatStrings() []string {
	strs := make([]string, len(_ImageFormatNames))
	copy(strs, _ImageFormatNames)
	return strs
}

// IsAImageFormat returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ImageFormat) IsAImageFormat() bool {
	for _, v := range _ImageFormatValues {
		if i == v {
			return true
		}
	}
	return false
}
