// Code generated by "enumer -type ColorFilter -trimprefix Color -transform lower -output filter_string.go"; DO NOT EDIT.

package encode

import (
	"fmt"
	"strings"
)

const _ColorFilterName = "nonedimmedredshiftwarmsunsetsepiavintageduskcoolbwicemoonlightneonpastel"

var _ColorFilterIndex = [...]uint8{0, 4, 10, 18, 22, 28, 33, 40, 44, 48, 50, 53, 62, 66, 72}

const _ColorFilterLowerName = "nonedimmedredshiftwarmsunsetsepiavintageduskcoolbwicemoonlightneonpastel"

func (i ColorFilter) String() string {
	if i >= ColorFilter(len(_ColorFilterIndex)-1) {
		return fmt.Sprintf("ColorFilter(%d)", i)
	}
	return _ColorFilterName[_ColorFilterIndex[i]:_ColorFilterIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ColorFilterNoOp() {
	var x [1]struct{}
	_ = x[ColorNone-(0)]
	_ = x[ColorDimmed-(1)]
	_ = x[ColorRedShift-(2)]
	_ = x[ColorWarm-(3)]
	_ = x[ColorSunset-(4)]
	_ = x[ColorSepia-(5)]
	_ = x[ColorVintage-(6)]
	_ = x[ColorDusk-(7)]
	_ = x[ColorCool-(8)]
	_ = x[ColorBW-(9)]
	_ = x[ColorIce-(10)]
	_ = x[ColorMoonlight-(11)]
	_ = x[ColorNeon-(12)]
	_ = x[ColorPastel-(13)]
}

var _ColorFilterValues = []ColorFilter{ColorNone, ColorDimmed, ColorRedShift, ColorWarm, ColorSunset, ColorSepia, ColorVintage, ColorDusk, ColorCool, ColorBW, ColorIce, ColorMoonlight, ColorNeon, ColorPastel}

var _ColorFilterNameToValueMap = map[string]ColorFilter{
	_ColorFilterName[0:4]:        ColorNone,
	_ColorFilterLowerName[0:4]:   ColorNone,
	_ColorFilterName[4:10]:       ColorDimmed,
	_ColorFilterLowerName[4:10]:  ColorDimmed,
	_ColorFilterName[10:18]:      ColorRedShift,
	_ColorFilterLowerName[10:18]: ColorRedShift,
	_ColorFilterName[18:22]:      ColorWarm,
	_ColorFilterLowerName[18:22]: ColorWarm,
	_ColorFilterName[22:28]:      ColorSunset,
	_ColorFilterLowerName[22:28]: ColorSunset,
	_ColorFilterName[28:33]:      ColorSepia,
	_ColorFilterLowerName[28:33]: ColorSepia,
	_ColorFilterName[33:40]:      ColorVintage,
	_ColorFilterLowerName[33:40]: ColorVintage,
	_ColorFilterName[40:44]:      ColorDusk,
	_ColorFilterLowerName[40:44]: ColorDusk,
	_ColorFilterName[44:48]:      ColorCool,
	_ColorFilterLowerName[44:48]: ColorCool,
	_ColorFilterName[48:50]:      ColorBW,
	_ColorFilterLowerName[48:50]: ColorBW,
	_ColorFilterName[50:53]:      ColorIce,
	_ColorFilterLowerName[50:53]: ColorIce,
	_ColorFilterName[53:62]:      ColorMoonlight,
	_ColorFilterLowerName[53:62]: ColorMoonlight,
	_ColorFilterName[62:66]:      ColorNeon,
	_ColorFilterLowerName[62:66]: ColorNeon,
	_ColorFilterName[66:72]:      ColorPastel,
	_ColorFilterLowerName[66:72]: ColorPastel,
}

var _ColorFilterNames = []string{
	_ColorFilterName[0:4],
	_ColorFilterName[4:10],
	_ColorFilterName[10:18],
	_ColorFilterName[18:22],
	_ColorFilterName[22:28],
	_ColorFilterName[28:33],
	_ColorFilterName[33:40],
	_ColorFilterName[40:44],
	_ColorFilterName[44:48],
	_ColorFilterName[48:50],
	_ColorFilterName[50:53],
	_ColorFilterName[53:62],
	_ColorFilterName[62:66],
	_ColorFilterName[66:72],
}

// ColorFilterString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ColorFilterString(s string) (ColorFilter, error) {
	if val, ok := _ColorFilterNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ColorFilterNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ColorFilter values", s)
}

// ColorFilterValues returns all values of the enum
func ColorFilterValues() []ColorFilter {
	return _ColorFilterValues
}

// ColorFilterStrings returns a slice of all String values of the enum
func ColorFilterStrings() []string {
	strs := make([]string, len(_ColorFilterNames))
	copy(strs, _ColorFilterNames)
	return strs
}

// IsAColorFilter returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ColorFilter) IsAColorFilter() bool {
	for _, v := range _ColorFilterValues {
		if i == v {
			return true
		}
	}
	return false
}
